language: r
cache: packages

os: 
  - osx
  - linux

# Workaround to get OSX build working,
# from https://github.com/travis-ci/travis-ci/issues/10295
fortran: false

r_packages:
  - devtools
  - hunspell

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  - KlausVigo/phangorn
  - ropensci/spelling

before_script:
  - sudo apt-get install -qq oracle-java8-installer # Java 8
  - sudo apt-get install oracle-java8-set-default
  - ./install_beast2
  # proselint
  - sudo pip install proselint
  # markdown-link-check, disabled until CERT_UNTRUSTED is fixed
  #- sudo apt-get install npm
  #- sudo npm install -g markdown-link-check

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'goodpractice::gp()'
  - proselint *.md | egrep -v "typography\.symbols\.curly_quotes"
  - cd scripts; ./build_cran
  # Disabled until CERT_UNTRUSTED is fixed
  #- ./check_dead_links

after_failure:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'goodpractice::gp()'
  - cat /home/travis/build/richelbilderbeek/tracerer/..Rcheck/00install.out
  - cat /home/travis/build/richelbilderbeek/tracerer/..Rcheck/00check.log
